ALTER TABLE `maquinas` ADD COLUMN `userId` int;
ALTER TABLE `maquinas` ADD COLUMN `createdAt` timestamp DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `maquinas` ADD COLUMN `updatedAt` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
