export {
  VENDA_DOCUMENTO_MAX_BYTES as COMPRA_DOCUMENTO_MAX_BYTES,
  VENDA_DOCUMENTO_TIPO_LABEL as COMPRA_DOCUMENTO_TIPO_LABEL,
  VENDA_DOCUMENTO_TIPOS as COMPRA_DOCUMENTO_TIPOS,
  type VendaDocumentoTipo as CompraDocumentoTipo,
} from "./vendaDocumentos";
